name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master   

# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
     
#       - uses: actions/checkout@v4
#         with:
#           lfs: true
#           fetch-depth: 2
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v4
#         with:
#            dotnet-version: "6.0.x"
#       - name: Restore
#         run: dotnet restore
#         working-directory: ./TestCICDWpf

#       - name: Build
#         run: dotnet build --configuration Release --no-restore
#         working-directory: ./TestCICDWpf

#       - name: Publish
#         run: dotnet publish --configuration Release --no-restore
#         working-directory: ./TestCICDWpf

#       - name: Upload
#         uses: actions/upload-artifact@v4
#         with:
#           name: Build
#           path: ./TestCICDWpf/bin/Release/net6.0-windows/publish/
        
  deploy:
    name: Deploy
    needs: build
    runs-on: windows-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: ./TestCICDWpf/bin/Release/net6.0-windows/publish/

      - name: Get version
        id: extractVersion
        shell: pwsh
        run: |
          $xml = [Xml] (Get-Content ./TestCICDWpf/TestCICDWpf.csproj)
          [string] $version = [Version] $xml.Project.PropertyGroup.Version
          echo "version=$($version)" >> $env:GITHUB_OUTPUT

      # - name: Create empty json file
      #   shell: pwsh
      #   run: |
      #       New-Item -Path . -Name "StateFolder" -ItemType "directory"
      #       New-Item -Path . -Name "StateFolder/.sync-state-v${{ steps.extractVersion.outputs.version }}.json" -ItemType "file"

      # - name: Deploy state file
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: eu-central-1.sftpcloud.io
      #     username: ea066c0c2dde4e91b2d8b8b881df1304
      #     password: JpADT8knYnuULHwDfSdTUd8oioPGF25E
      #     protocol: ftps
      #     port: 21
      #     # dry-run: true
      #     local-dir: ./StateFolder/
      #     server-dir: Project/
      
      # - name: Delete files
      #   shell: pwsh
      #   run: Remove-Item -Path "StateFolder/*.json" -Force

      - name: Deploy publish
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: eu-central-1.sftpcloud.io
          username: ea066c0c2dde4e91b2d8b8b881df1304
          password: JpADT8knYnuULHwDfSdTUd8oioPGF25E
          protocol: ftps
          port: 21
          state-name: .sync-state-v${{ steps.extractVersion.outputs.version }}.json
          local-dir: ./TestCICDWpf/bin/Release/net6.0-windows/publish/
          server-dir: Project/

      - name: Deploy version
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: eu-central-1.sftpcloud.io
          username: ea066c0c2dde4e91b2d8b8b881df1304
          password: JpADT8knYnuULHwDfSdTUd8oioPGF25E
          protocol: ftps
          port: 21
          local-dir: ./.github/
          server-dir: Project/Version/
