name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "MyTag/v*"    

env:
   DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
           dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore ./TestCICDWpf.sln

      - name: Build
        run: dotnet build ./TestCICDWpf.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./TestCICDWpf.sln --configuration Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-restore

      - uses: actions/create-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.Token_github }}
        with:
           tag_name: ${{ github.ref }}
           release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v4
        with:
           github-token: ${{ secrets.Token_github }}
           pattern: ./TestCICDWpf/bin/Release/net6.0-windows/win-x64/publish/*.exe
           release-url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
           name: Build
           path: ./TestCICDWpf/bin/Release/net6.0-windows/win-x64/publish