name: Deploy

on:
  push:
    branches:
      - master    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/ckeckout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore
      working-directory: ./TestCICDWpf

    - name: Build
      run: dotnet build -c Release
      working-directory: ./TestCICDWpf

    - name: Test
      run: dotnet build -c Release

    - name: Publish
      run: dotnet publish -c Release
      working-directory: ./TestCICDWpf

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: ./TestCICDWpf/bin/Release/net6.0-windows/*.msix