name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master    

env:
   DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore ./TestCICDWpf.sln

      - name: Build
        run: dotnet build ./TestCICDWpf.sln --configuration Release --no-restore

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
           name: Build
           path: ./TestCICDWpf/TestCICDWpf/bin/Release/net6.0-windows/publish/TestCICDWpf.exe
  